# Generated by Django 3.2 on 2022-04-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crim', models.PositiveIntegerField()),
                ('indus', models.PositiveIntegerField()),
                ('nox', models.PositiveIntegerField()),
                ('dis', models.PositiveIntegerField()),
                ('rad', models.PositiveIntegerField()),
                ('tax', models.PositiveIntegerField()),
                ('B', models.PositiveIntegerField()),
            ],
        ),
    ]
